# Generated by Django 4.2.11 on 2024-04-22 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('max_height', models.IntegerField(choices=[(1, 'Tall'), (2, 'Medium'), (3, 'Short')])),
                ('spread', models.IntegerField(choices=[(1, 'Wide'), (2, 'Moderate'), (3, 'Compact')])),
                ('flowering_season', models.IntegerField(choices=[(1, 'Spring'), (2, 'Summer'), (3, 'Fall'), (4, 'None')])),
                ('sunlight_exposure', models.IntegerField(choices=[(1, 'Full Sun'), (2, 'Partial Shade'), (3, 'Shade')])),
                ('pruning_frequency', models.IntegerField(choices=[(1, 'Regular'), (2, 'Occasional')])),
                ('watering_needs', models.IntegerField(choices=[(1, 'Low'), (2, 'Moderate'), (3, 'High')])),
                ('fertilization', models.IntegerField(choices=[(1, 'Regular'), (2, 'Occasional')])),
                ('pest_disease_resistance', models.IntegerField(choices=[(1, 'Resistant'), (2, 'Susceptible')])),
            ],
        ),
    ]
