# Generated by Django 4.2.11 on 2024-04-26 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_garden_app', '0004_plant_maintenance'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Plant_Maintenance',
            new_name='PlantMaintenance',
        ),
    ]
