# Generated by Django 4.2.11 on 2024-04-26 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_garden_app', '0005_rename_plant_maintenance_plantmaintenance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantmaintenance',
            name='task',
            field=models.IntegerField(choices=[(1, 'Przycinanie'), (2, 'Nawożenie')], verbose_name='Zadanie'),
        ),
    ]
