# Generated by Django 4.2.11 on 2024-04-29 10:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('my_garden_app', '0006_alter_plantmaintenance_task'),
    ]

    operations = [
        migrations.CreateModel(
            name='Garden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nazwa ogrodu')),
            ],
        ),
        migrations.CreateModel(
            name='PlantGarden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Data posadzenia')),
                ('location', models.CharField(max_length=100, verbose_name='Lokalizacja')),
                ('garden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_garden_app.garden')),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_garden_app.plant')),
            ],
        ),
        migrations.CreateModel(
            name='MaintenanceMonthlySchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[('1', 'Nie rozpoczęto'), ('2', 'W trakcie'), ('3', 'Zakończono')], verbose_name='Status realizacji')),
                ('completion_date', models.DateField(verbose_name='Data realizacji')),
                ('month', models.IntegerField(choices=[(1, 'Styczeń'), (2, 'Luty'), (3, 'Marzec'), (4, 'Kwiecień'), (5, 'Maj'), (6, 'Czerwiec'), (7, 'Lipiec'), (8, 'Sierpień'), (9, 'Wrzesień'), (10, 'Październik'), (11, 'Listopad'), (12, 'Grudzień')], verbose_name='Miesiąc')),
                ('plant_garden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_garden_app.plantgarden', verbose_name='Roślina')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_garden_app.plantmaintenance', verbose_name='Zadanie')),
            ],
        ),
        migrations.AddField(
            model_name='garden',
            name='plants',
            field=models.ManyToManyField(through='my_garden_app.PlantGarden', to='my_garden_app.plant'),
        ),
        migrations.AddField(
            model_name='garden',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Użytkownik'),
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(verbose_name='Komentarz')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Data utworzenia')),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_garden_app.plant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
